name: Document generation using Doxygen

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cppcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install doxygen
      run: sudo apt-get -y install doxygen
    - name: Run doxygen
      run: make -C 3_Implementation/ documentation doc